services:
  pg:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_LISTEN_PORT=8080   # <- веб-порт
    ports:
      - "127.0.0.1:823:8080"       # <- хост:823 → контейнер:8080
    restart: unless-stopped

  pg-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./migration:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:pg:5432
    ports:
      - "127.0.0.1:5432:5432"

  swagger:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.26.2-alpine3.22
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - .:/code
